# Generated by Django 2.1 on 2018-08-14 20:39

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180814_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('desc', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(null=True, upload_to=posts.models.generate_filename)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='posts.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='updated_at',
        ),
    ]
