# Generated by Django 2.1 on 2018-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180814_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
