# Generated by Django 2.1 on 2018-08-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180814_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
